project:
  type: website
  output-dir: docs

website:
  title: "PET/CT"
  
  navbar:
    left:
      - text: "Blog"
        href: index.qmd
      - text: "NSCLC"
        href: posts/NSCLC/staging.qmd
      - text: "SCLC"
        href: posts/SCLC/staging.qmd        
      - text: "Prostate"
        href: posts/prostate/staging.qmd

    right:
      - text: "About"      
        href: posts/about/about.qmd       
      - icon: github
        href: https://github.com/
    search: true

  sidebar:
    - title: "NSCLC"
      contents:
        - posts/NSCLC/staging.qmd
    - title: "SCLC"
      contents:
        - posts/SCLC/staging.qmd
    - title: "prostate"
      contents:
        - posts/prostate/staging.qmd            
    
format:
  html:
    theme: cosmo
    relative-resources: true
    css: styles/tooltip.css
    csl: styles/nuclear-medicine-and-molecular-imaging.csl
    toc: true
    toc-depth: 4
    include-after-body:
      - text: |
          <script src="/scripts/tooltip.js"></script>
    
    comments:
      utterances:
        repo: RadiationSafetyNM/website